from bson.objectid import ObjectId

anndata_test_models = {
    "data_arrays": {
        "anndata_test.h5ad Cells": {
            "name": "anndata_test.h5ad Cells",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "AA",
                "AB",
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AH",
                "AI",
                "AJ",
                "BA",
                "BB",
                "BC",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "CA",
                "CB",
                "CC",
                "CD",
                "CE",
                "CF",
                "CG",
                "CH",
                "CI",
                "CJ",
                "DA",
                "DB",
                "DC",
                "DD",
                "DE",
                "DF",
                "DG",
                "DH",
                "DI",
                "DJ",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Study",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Foo Cells": {
            "name": "Foo Cells",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "AA",
                "AB",
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AH",
                "AI",
                "AJ",
                "BA",
                "BB",
                "BC",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "CA",
                "CB",
                "CC",
                "CD",
                "CE",
                "CF",
                "CG",
                "CH",
                "CI",
                "CJ",
                "DA",
                "DB",
                "DC",
                "DD",
                "DE",
                "DF",
                "DG",
                "DH",
                "DI",
                "DJ",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Foo Expression": {
            "name": "Foo Expression",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                4.0,
                3.0,
                2.0,
                1.0,
                3.0,
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                5.0,
                4.0,
                3.0,
                2.0,
                1.0,
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                5.0,
                5.0,
                4.0,
                1.0,
                1.0,
                1.0,
                2.0,
                3.0,
                4.0,
                5.0,
                5.0,
                4.0,
                3.0,
                2.0,
                1.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Bar Cells": {
            "name": "Bar Cells",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "AA",
                "AB",
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AH",
                "AI",
                "AJ",
                "BA",
                "BB",
                "BC",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "CA",
                "CB",
                "CC",
                "CD",
                "CE",
                "CF",
                "CG",
                "CH",
                "CI",
                "CJ",
                "DA",
                "DB",
                "DC",
                "DD",
                "DE",
                "DF",
                "DG",
                "DH",
                "DI",
                "DJ",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Bar Expression": {
            "name": "Bar Expression",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                2.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                3.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                4.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Baz Cells": {
            "name": "Baz Cells",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "AA",
                "AB",
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AH",
                "AI",
                "AJ",
                "BA",
                "BB",
                "BC",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "CA",
                "CB",
                "CC",
                "CD",
                "CE",
                "CF",
                "CG",
                "CH",
                "CI",
                "CJ",
                "DA",
                "DB",
                "DC",
                "DD",
                "DE",
                "DF",
                "DG",
                "DH",
                "DI",
                "DJ",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Baz Expression": {
            "name": "Baz Expression",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                3.0,
                3.0,
                2.0,
                1.0,
                1.0,
                2.0,
                3.0,
                4.0,
                4.0,
                5.0,
                4.0,
                4.0,
                3.0,
                2.0,
                1.0,
                1.0,
                2.0,
                3.0,
                5.0,
                5.0,
                4.0,
                5.0,
                4.0,
                2.0,
                1.0,
                1.0,
                2.0,
                3.0,
                5.0,
                5.0,
                3.0,
                3.0,
                4.0,
                2.0,
                1.0,
                1.0,
                2.0,
                5.0,
                5.0,
                4.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Qux Cells": {
            "name": "Qux Cells",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "AA",
                "AB",
                "AC",
                "AD",
                "AE",
                "AF",
                "AG",
                "AH",
                "AI",
                "AJ",
                "BA",
                "BB",
                "BC",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "CA",
                "CB",
                "CC",
                "CD",
                "CE",
                "CF",
                "CG",
                "CH",
                "CI",
                "CJ",
                "DA",
                "DB",
                "DC",
                "DD",
                "DE",
                "DF",
                "DG",
                "DH",
                "DI",
                "DJ",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
        "Qux Expression": {
            "name": "Qux Expression",
            "cluster_name": "anndata_test.h5ad",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
                5.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
        },
    },
    "gene_models": {
        "Foo": {
            "name": "Foo",
            "searchable_name": "foo",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "gene_id": None,
        },
        "Bar": {
            "name": "Bar",
            "searchable_name": "bar",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "gene_id": None,
        },
        "Baz": {
            "name": "Baz",
            "searchable_name": "baz",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "gene_id": None,
        },
        "Qux": {
            "name": "Qux",
            "searchable_name": "qux",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a337"),
            "study_id": ObjectId("5d276a50421aa9117c982845"),
            "gene_id": None,
        },
    },
}

