repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language: system
      # Using args here is not recommended by Black:
      # https://black.readthedocs.io/en/stable/version_control_integration.html
      # But since we only have one argument here, and
      # we don't force developers to use editor plugins,
      # putting the args here seems to be fine
      args: [ingest/, --skip-string-normalization]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: cd tests; pytest -v
        language: system
        types: [python]
        stages: [push]