from bson.objectid import ObjectId

one_column_feature_file_data_models = {
    "data_arrays": {
        "one_column_feature_file_data_models.mtx Cells": {
            "name": "one_column_feature_file_data_models.mtx Cells",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "M1_S4.TGTACAGGTCGGTGTC",
                "M1_S4.TCCTCTTGTCTCCTGT",
                "M1_S4.TGAATGCCATGGCTGC",
                "M1_S4.CTACGGGTCCTGCTAC",
                "M1_S3.ATTCCATGTATCGGTT",
                "M1_S3.CTGCCATCACGTTGGC",
                "M1_S3.CATACTTCAGTCTGGC",
                "M1_S4.CGTTAGAGTGAGTAAT",
                "M1_S4.GCACATAGTCAAGCGA",
                "M1_S4.CATAGACCAGTATTCG",
                "M1_S3.CACGTGGCATGGATCT",
                "M1_S4.CGAAGTTCAATGTCAC",
                "M1_S4.AACGTCAAGTCGCCAC",
                "M1_S3.ATCCACCTCGACGAGA",
                "M1_S3.CATCGGGTCACGTAGT",
                "M1_S3.GTATTTCCAAACACCT",
                "M1_S4.TTCTTGACACACAGCC",
                "M1_S3.TTTGATCAGACTCAAA",
                "M1_S3.TTGGGATCACTGTCCT",
                "M1_S3.CTCAACCAGCAATAAC",
                "M1_S4.TGGAACTGTCACTACA",
                "M1_S4.TTGCATTAGGACGCAT",
                "M1_S4.GAGCCTGTCCACTTCG",
                "M1_S3.AGATGCTGTCGAGTGA",
                "M1_S4.ACACAGTCAGGCTACC",
                "M1_S3.GGCTTTCGTACGCTAT",
                "M1_S3.TTCCTTCGTCGTTTCC",
                "M1_S4.AACCATGGTGGCTAGA",
                "M1_S4.CATTGTTGTATCAGGG",
                "M1_S4.CCATCACGTGCGAACA",
                "M1_S4.CTCCACAGTTCGTAAC",
                "M1_S3.GGGTAGACAAGACCTT",
                "M1_S4.GACCCAGAGCTTAAGA",
                "M1_S3.TAGAGTCTCTCCAATT",
                "M1_S3.GTTACCCCATCTGCGG",
                "M1_S4.AATGACCCACGTGTGC",
                "M1_S4.TAGCACATCTAGCCAA",
                "M1_S4.GTTCATTCAGCATACT",
                "M1_S4.CAAGACTAGCCTCAAT",
                "M1_S3.CACTAAGCATCAACCA",
                "M1_S3.TGAATGCTCAAACGAA",
                "M1_S3.TAGGTACGTCGTGTTA",
                "M1_S4.AGTACCAAGACGCCCT",
                "M1_S4.AGTAGTCTCGTAGTCA",
                "M1_S4.ACGGTCGTCATAGGCT",
                "M1_S4.CAGGTATGTGAATGAT",
                "M1_S4.CCCATTGTCTGCGGCA",
                "M1_S4.GGAATGGTCTCACCCA",
                "M1_S4.TGTGAGTCATGGGAAC",
                "M1_S3.GTAGCTACAGCTTTCC",
                "M1_S4.GAACACTAGGACGGAG",
                "M1_S3.TCGCACTTCGTCCTTG",
                "M1_S3.AGCGTATTCGCAGATT",
                "M1_S3.GTCTTTATCGTCAACA",
                "M1_S4.TATTGCTGTTGTGTTG",
                "M1_S4.TCGCAGGCAGTATGAA",
                "M1_S4.TGCGATAGTCGAGTGA",
                "M1_S3.CGGGACTCATTCGGGC",
                "M1_S4.TGGAACTTCTATTGTC",
                "M1_S3.TATTCCAAGAGGCGGA",
                "M1_S3.CCTTGTGGTGACTGTT",
                "M1_S3.ATGGTTGCAACAGCCC",
                "M1_S3.TGAGTCATCTCAAAGC",
                "M4_S14.CAAAGAACAAGAAATC",
                "M4_S13.TTGCATTTCCATTTGT",
                "M4_S14.TTGCATTTCCATTTGT",
                "M5_S30.AGAACCTAGAAGGGAT",
                "M5_S29.AGTAGTCCACATACGT",
                "M5_S29.ATTCACTCAACGACAG",
                "M5_S30.TGAGACTGTGGGCTCT",
                "M5_S29.GATCAGTTCTCAAAGC",
                "M5_S30.TCGCTCACAGAGGTAC",
                "M5_S29.TTAATCCCATACGCAT",
                "M5_S29.GATGAGGCATTCAGGT",
                "M5_S29.CTCCTCCGTAGTGCGA",
                "M5_S30.AGAACCTGTTCAGCTA",
                "M5_S30.AGTTAGCTCTCCCAAC",
                "M5_S29.TCCTTTCGTTACACTG",
                "M5_S29.TTGGGATTCCTTTGAT",
                "M5_S30.GTCGAATAGGGTTAAT",
                "M5_S30.CTTCTCTTCAGGAACG",
                "M5_S30.TCCAGAAGTAAGATCA",
                "M5_S30.CGGGACTTCACGTAGT",
                "M5_S29.TCGGGCAAGTATTCCG",
                "M5_S30.GAGGCCTGTATCCTCC",
                "M5_S30.AAGTGAAGTGGTCTGC",
                "M5_S29.GTCTGTCCAGAGTAAT",
                "M5_S30.GTGTTAGTCTATTGTC",
                "M5_S29.GGTGTTACAGACAATA",
                "M5_S30.AGGAAATAGGGTTAGC",
                "M5_S29.TTGTTGTCAGGTAGTG",
                "M5_S29.GTATTGGTCAAAGGAT",
                "M5_S29.TCAATTCCAGTTCTAG",
                "M5_S29.GACTCAAAGGGACAGG",
                "M5_S29.GCTACCTAGCGCCGTT",
                "M5_S29.AATGGCTTCCATGAGT",
                "M5_S29.ACGTTCCTCTTCCCGA",
                "M5_S30.GACAGCCCATCCAATG",
                "M5_S30.GGTTAACAGAAGTCTA",
                "M5_S30.TTGCCTGTCCGAGTGC",
                "M5_S30.TACTTGTTCACCGGTG",
                "M5_S30.CAACGGCCACGCGTCA",
                "M5_S29.TACCGGGTCGACATAC",
                "M5_S30.AAAGGGCCATCGGAGA",
                "M5_S29.CAGCCAGAGGTCATCT",
                "M5_S30.CTAGGTATCTCTCTTC",
                "M5_S29.GGTGTCGAGACATACA",
                "M5_S30.CGTAGTAGTGCAATAA",
                "M5_S30.AAGAACAAGGGACCAT",
                "M5_S30.ATTCGTTCATCGAAGG",
                "M5_S30.ACGATGTCAATCTGCA",
                "M5_S29.ACACAGTGTCCAGTTA",
                "M5_S29.TGAATGCAGATCGCCC",
                "M5_S30.CTGTATTGTTTACGAC",
                "M5_S29.GTGGAAGAGGAAAGTG",
                "M5_S29.AGACTCAAGGGATCAC",
                "M5_S29.CTCAGGGGTGCGAACA",
                "M5_S29.TCACTATAGAGCCGAT",
                "M5_S29.GCCGATGCAGCGTGCT",
                "M5_S29.CTCTCGAAGAAGCTCG",
                "M5_S29.GGTTCTCCAGGTGACA",
                "M5_S29.GAGTTACTCGGAGTGA",
                "M5_S29.TCTGCCACAGTAACGG",
                "M5_S29.CTCCGATGTAAGTTGA",
                "M5_S29.TACGCTCTCAGCGCAC",
                "M5_S30.AGGATCTCAGGCACAA",
                "M5_S30.CCTCTCCCACATTCGA",
                "M5_S29.AATCGACAGTCGCTAT",
                "M5_S30.GCTTTCGGTCCACACG",
                "M5_S29.ATTCAGGTCTGTGTGA",
                "M5_S29.TACAGGTAGTTGCATC",
                "M5_S30.CGTGCTTCACCCATAA",
                "M5_S29.GAAGGACCAATCAAGA",
                "M5_S30.GTATTGGAGCACCGAA",
                "M5_S30.GGAGATGCATGAATCC",
                "M5_S30.ACGCACGGTTGTGGAG",
                "M5_S29.GATTTCTCACTAGTAC",
                "M5_S29.AGCCAATGTCGGTACC",
                "M5_S29.GTAGATCTCAGACCTA",
                "M5_S30.AGCGATTAGTCCTGCG",
                "M5_S29.TGTGATGCACGGTGAA",
                "M5_S30.CGACAGCAGCGCATCC",
                "M5_S29.CTACATTCAATTGAAG",
                "M5_S29.GGGCTCAGTCAGTTTG",
                "M5_S30.ATGCGATCAACGTATC",
                "M5_S29.TTCTCTCTCATTACTC",
                "M5_S29.GTTAGACCATGAGAAT",
                "M5_S29.TCTTAGTGTCTGATCA",
                "M5_S30.ACATGCATCCTCACTG",
                "M5_S29.GGGTGAAAGAGATTCA",
                "M5_S29.TGTTCTAGTTGATGTC",
                "M5_S30.ACTTTGTAGAGCCGAT",
                "M5_S30.CTCCTCCAGAACAAGG",
                "M5_S30.GTTGTGAGTACGCGTC",
                "M5_S30.AGGGTTTAGCGTCAGA",
                "M5_S30.CTGAATGCAAAGGGCT",
                "M5_S29.GGGAGTAGTGGCTACC",
                "M5_S29.GTGCTGGCATGAGATA",
                "M5_S29.TCATACTAGTTACGAA",
                "M5_S30.CCCTTAGGTAGTTAGA",
                "M5_S30.CCATCACTCAAACGAA",
                "M5_S30.GGTGAAGAGAGAATCT",
                "M5_S29.ATTTCACGTGGTTTGT",
                "M5_S30.GATGATCTCATTACGG",
                "M5_S30.TCCTCCCTCTGTCAGA",
                "M5_S29.GACCAATAGGCAGGGA",
                "M5_S29.AGACACTGTAGAGGAA",
                "M5_S29.TCATTACAGAACTTCC",
                "M5_S29.GCCGTGAGTATGAGGC",
                "M5_S30.CGAATTGGTAGTGCGA",
                "M5_S30.GTATTGGCAACGGTAG",
                "M5_S30.TGTGAGTTCAACCTTT",
                "M5_S29.CATTTCAAGTGAACAT",
                "M5_S29.GAGAAATTCCGCTGTT",
                "M5_S30.CATACAGTCACTTATC",
                "M5_S29.GGGCTCAAGATAGTCA",
                "M5_S29.GCTTTCGTCAGTGGGA",
                "M5_S29.TCCTTCTGTGGAGAAA",
                "M5_S30.CGTTCTGCACTTGACA",
                "M5_S29.ACAACCATCATGGGAG",
                "M5_S29.GTTGAACCAAGACGAC",
                "M5_S30.TTTACTGCACCGCTGA",
                "M5_S29.ACTCTCGCAGCTGAAG",
                "M5_S29.TAGACCAAGATACGAT",
                "M5_S30.CAAAGAAGTCACGTGC",
                "M5_S30.CATGGTACAGGCTATT",
                "M5_S30.ACTCTCGCAAATACAG",
                "M5_S30.AGGTGTTGTTGTCCCT",
                "M5_S29.GACCAATAGACGCATG",
                "M5_S30.TAGACCATCTTCGGTC",
                "M5_S30.ATTACCTAGCATGTTC",
                "M5_S29.AGGGCTCTCCGGACGT",
                "M5_S29.AAAGGGCAGAGGTATT",
                "M5_S30.TCAGGTAGTGAAAGTT",
                "M5_S30.CTAGACATCACTCTTA",
                "M5_S30.TCCTTCTCATCTGTTT",
                "M5_S29.ATATCCTAGCATCCCG",
                "M5_S30.TGTGCGGCAGCGTAGA",
                "M5_S29.TGGAACTTCTGCATAG",
                "M5_S29.TGACAGTAGCAGCAGT",
                "M5_S29.ACCAACAGTCTTCCGT",
                "M5_S29.GTCCACTCATGGGATG",
                "M5_S30.GTACAACAGCATCCTA",
                "M5_S30.TACAACGGTTGGATCT",
                "M5_S29.CACCAAATCAAGAAAC",
                "M5_S30.GTCTGTCGTGCCCAGT",
                "M5_S29.CGACAGCTCAACTGAC",
                "M5_S29.TACCCGTCAAGAAATC",
                "M5_S29.GTTGTAGTCTTGCGCT",
                "M5_S29.CCACCATTCGCACGGT",
                "M5_S29.CTTACCGAGCGAATGC",
                "M5_S29.GCCGTGAGTTGCCATA",
                "M5_S29.TCAGTGAGTTTACGAC",
                "M5_S30.TGTCAGATCATCGCAA",
                "M5_S30.GAAACCTCATAGAATG",
                "M5_S30.TTCTCTCCAACCCGCA",
                "M5_S29.TGTACAGAGAGTTGAT",
                "M5_S30.TCACACCTCAGGTAAA",
                "M5_S30.ACTATGGAGCACACAG",
                "M5_S29.GCCCAGAAGGAACTAT",
                "M5_S29.GTAGATCCAGAGTCTT",
                "M5_S29.TCATTGTCAACGGGTA",
                "M5_S30.CGAGTTACAAGTATCC",
                "M5_S30.TAGGAGGAGTGAGGTC",
                "M5_S30.TCAAGACAGGTTACCT",
                "M5_S29.TCATTCATCGCAGTCG",
                "M5_S30.TTTCATGGTGGTGATG",
                "M5_S29.GTTCGCTTCGGTAACT",
                "M5_S30.TTTGGAGAGGCTCCCA",
                "M5_S30.CCGCAAGGTTATGTGC",
                "M5_S30.ATGGGTTAGGCGAACT",
                "M5_S29.AATGAAGTCATGAGGG",
                "M5_S29.ATTACTCGTTGTATGC",
                "M5_S29.CACTGAAAGGACAGTC",
                "M5_S29.CAGATACAGTAGGGTC",
                "M5_S30.TGGAACTGTCCAATCA",
                "M5_S30.CATGCCTCAAATGAAC",
                "M5_S29.TCGGGTGTCGAACGCC",
                "M5_S30.CCTGCATCACCTATCC",
                "M5_S29.GAAGCCCAGGGTGAAA",
                "M6_S31.CAATGACAGTAACCGG",
                "M6_S31.GAGGCAATCGACTCCT",
                "M6_S31.TCACGCTGTGAGATCG",
                "M6_S31.CAATACGAGGCCACTC",
                "M6_S31.GTGTAACCATCTGGGC",
                "M6_S31.CGGACACCACAGTCAT",
                "M6_S31.GTAGCTACATGACTAC",
                "M6_S31.TTACGCCAGACGGATC",
                "M6_S31.GGGAGATGTATACGGG",
                "M6_S31.GTCTAGACATGTCGTA",
                "M6_S31.CCATAAGTCTGGTCAA",
                "M6_S31.GACTCTCAGGTGGGTT",
                "M6_S31.CCAAGCGGTGGGTCAA",
                "M6_S31.AGAAGCGCATGGTGGA",
                "M6_S31.CAACAACTCGGAACTT",
                "M6_S31.TAACTTCAGACCATTC",
                "M6_S31.CGATGCGTCGCTGTCT",
                "M6_S31.GCATTAGCAACGGTAG",
                "M6_S31.CAACAGTTCTAGCCAA",
                "M6_S31.TCCCATGAGGTTTACC",
                "M6_S31.GCCATTCTCGACACTA",
                "M6_S31.TGGATCAAGTTGGAGC",
                "M6_S31.AGGGCCTCATGACGGA",
                "M6_S31.TGTGCGGAGCCTCAAT",
                "M6_S31.GAGTCATCACACTGGC",
                "M6_S31.ACATCCCAGAGGTCAC",
                "M6_S31.GGCACGTGTATGAAGT",
                "M6_S31.TCGAACAAGCGCCTCA",
                "M6_S31.CCGTGAGTCGCTCTAC",
                "M6_S31.GACACGCGTCTTTATC",
                "M6_S31.TGTGTGAGTCCAACGC",
                "M6_S31.ATGCATGCACCGTGAC",
                "M6_S31.TCCACGTGTCTGCGCA",
                "M6_S31.GAGACCCCACGGTGTC",
                "M6_S31.TTCCGTGGTTCTTCAT",
                "M6_S31.CAGATCACAGATCATC",
                "M6_S31.GTAGCTATCAGCGGAA",
                "M6_S31.TCACGCTAGAATTCAG",
                "M6_S31.CCTAACCGTCCTATAG",
                "M6_S31.ACAGAAAGTTTCCAAG",
                "M6_S31.TCGACGGAGTGTTCAC",
                "M6_S31.TTCGGTCGTTCTAACG",
                "M6_S31.TGATCTTAGGATGCGT",
                "M6_S31.TGCAGTATCGAGATGG",
                "M6_S31.GGAGGATCATTGTACG",
                "M6_S31.GTCGAATAGCGGTAAC",
                "M6_S31.CGTAAGTAGCGGATCA",
                "M6_S31.ATTTACCAGATGTAGT",
                "M6_S31.GATTCGAAGACTCCGC",
                "M6_S31.GGTGAAGAGAGCAAGA",
                "M6_S31.GTGTGGCAGTCAGGGT",
                "M6_S31.AAAGGGCGTCTTCATT",
                "M6_S31.GTCACTCAGGTCGTAG",
                "M6_S31.TCACGCTTCACCGGTG",
                "M6_S31.GGGTCTGGTGAAGCGT",
                "M6_S31.ATTCTTGCAGTCGCAC",
                "M6_S31.ACTATTCGTACTTCCC",
                "M6_S31.TAGTGCATCTGCTAGA",
                "M6_S31.TGCGGCACAATGAAAC",
                "M6_S31.GGGTATTAGACCAGAC",
                "M6_S31.GGGTCACTCCAAGCTA",
                "M6_S31.TTCCGGTGTGCCTGAC",
                "M6_S31.GTCTCACTCTAATTCC",
                "M6_S31.ATTTCTGGTTGGGAAC",
                "M6_S31.CCGATGGCACTCCTTG",
                "M6_S31.TGTGTGATCTTTCAGT",
                "M6_S31.ACAGAAATCCCTATTA",
                "M7_S28.TAACTTCAGACTGTTC",
                "M7_S28.GGGAGTACAAACTCGT",
                "M7_S27.TGGGCTGGTATGACAA",
                "M7_S28.GGTGATTTCAGACCCG",
                "M7_S28.AGGGTCCTCGAAGGAC",
                "M7_S28.TTCTGTAGTTTAGAGA",
                "M7_S28.CTACCCAGTGCCCACA",
                "M7_S28.TCCCATGCATCCTTGC",
                "M7_S28.AAAGTCCTCCTCTGCA",
                "M7_S28.TGAGGAGAGTAGTGCG",
                "M7_S27.TCTCACGAGCACTTTG",
                "M7_S28.GTTCGCTCATTGCTTT",
                "M7_S27.TAACCAGCAGAAATTG",
                "M7_S28.TTGATGGAGCATGAAT",
                "M7_S27.TTACAGGAGCTTAGTC",
                "M7_S27.CACGTGGCAGAGGTAC",
                "M7_S27.CCCGAAGTCCTCAGAA",
                "M7_S28.CGGGTCAGTCCCGGTA",
                "M7_S28.TCGGGACGTTAAGGGC",
                "M7_S28.TCCTCGAAGGAGAATG",
                "M7_S27.TGAGGGAAGTCGAATA",
                "M7_S27.AGTAACCTCACGGACC",
                "M7_S28.AACAAAGAGTATGATG",
                "M7_S28.CATTGCCAGATAACGT",
                "M7_S28.CGGAACCTCCCTGTTG",
                "M7_S28.GCTTTCGCATAGAAAC",
                "M7_S27.AAACGAACAGAGACTG",
                "M7_S28.GTGTTAGCATTGGGAG",
                "M7_S28.CTCAGAATCAAGCTGT",
                "M7_S28.GCGTGCATCTCTCTAA",
                "M7_S28.TGGGCTGGTATGAAGT",
                "M7_S27.CTCCCAAAGTTGCTGT",
                "M7_S28.ACTCTCGCACGAGAAC",
                "M7_S28.GGTCTGGCACAGTCGC",
                "M7_S27.CACTGGGGTGTCTAAC",
                "M7_S28.TCATTTGGTTCCGTTC",
                "M7_S28.AACCTGATCATTTACC",
                "M7_S27.GTGCTTCTCTTGGGCG",
                "M7_S27.TATTCCACAAACTAAG",
                "M7_S28.TGGATGTGTTACAGCT",
                "M7_S27.GGAGAACCACCTAAAC",
                "M7_S28.AAAGAACCATCCGGCA",
                "M7_S27.GCCTGTTGTCGTGGTC",
                "M7_S28.TGAGGGACAAGCAGGT",
                "M7_S28.CAAGACTCAATCGCGC",
                "M7_S27.TAGACTGTCCATGATG",
                "M7_S28.GAAACCTAGTAAGGGA",
                "M7_S28.GCTTTCGCACTGCATA",
                "M7_S27.ATCATTCGTGCAATGG",
                "M7_S27.CATGCGGAGGAAAGGT",
                "M7_S27.AGATAGAGTGGGTATG",
                "M7_S28.TTAGGGTAGCATCCCG",
                "M7_S27.AAGCGTTCAGCTGTGC",
                "M7_S28.CTTGAGAGTAGTCCTA",
                "M7_S27.AATTTCCCAGAACCGA",
                "M7_S28.TCACGCTGTGAGCTCC",
                "M7_S27.AGTACTGCAACCTATG",
                "M7_S28.TCAATTCTCTGATGGT",
                "M7_S27.AGCGCTGCAGTAGTTC",
                "M7_S28.TTGTGGAGTGTAAACA",
                "M7_S27.GGGACTCCAACAAAGT",
                "M7_S27.ATCGGATAGTGTAGAT",
                "M7_S28.GTCAAGTTCGAGCTGC",
                "M7_S27.GGGTAGAAGTCCCAAT",
                "M7_S27.TTACTGTCAATCGCCG",
                "M7_S27.GTATTGGGTCCAGAAG",
                "M7_S27.GAGGGATTCACTGTCC",
                "M7_S28.GTGGCGTCACCGGAAA",
                "M7_S28.TCTTCCTGTTTGGGTT",
                "M7_S27.TGGATGTGTCTGTTAG",
                "M7_S28.GTACAGTTCTGCGAGC",
                "M7_S27.GCCATGGTCCCATACC",
                "M7_S28.GGTTAACTCTTACGGA",
                "M7_S27.AACACACAGCAATTCC",
                "M7_S28.CGAGGCTAGCTGACAG",
                "M7_S28.ACAGGGAGTTTAGTCG",
                "M7_S28.TCAGGTATCCATAGAC",
                "M7_S28.CTCAAGACAAGATTGA",
                "M7_S27.CGATCGGCATTGCAAC",
                "M7_S28.TCTGCCAGTTTACTTC",
                "M7_S27.ATACCTTAGATGACCG",
                "M7_S28.TAGGGTTAGAAACCCG",
                "M7_S28.AGCTCAATCATGCATG",
                "M7_S27.TATGTTCGTTTACGTG",
                "M7_S28.TCAAGTGAGCAAGTCG",
                "M7_S28.CTGTGGGCAATCTCGA",
                "M7_S28.ACAAGCTCACCTGAAT",
                "M7_S28.CAATCGATCCAAAGGG",
                "M7_S28.GAACTGTAGTCATCCA",
                "M7_S27.TCAGTTTGTCAGCTTA",
                "M7_S27.AAGACTCCACGACAAG",
                "M7_S28.CCACGAGAGTGCACAG",
                "M7_S28.TAGGTTGCATTGGATC",
                "M7_S28.GTTAGACGTTCAAAGA",
                "M7_S28.GGAACCCGTGAGTAAT",
                "M7_S27.TTCCTCTCAGCCCACA",
                "M7_S28.ACCAACAGTTGCATCA",
                "M7_S28.GATTTCTCAGGGCTTC",
                "M7_S27.TTGTGTTGTTAGGGTG",
                "M7_S27.GACCGTGGTAGCTTAC",
                "M7_S27.GTAGAGGGTAGCGTTT",
                "M7_S27.GTTATGGGTGTGTGGA",
                "M7_S27.AATGGCTCATAGATGA",
                "M7_S27.CTCAACCTCCACAGCG",
                "M7_S28.ATTCTACCAATTCACG",
                "M7_S28.CACATGAGTTGTTGTG",
                "M7_S27.GGCTTGGGTGACTATC",
                "M7_S28.TACGTCCCACCTGCTT",
                "M7_S27.AGCCAGCTCAAGGTGG",
                "M7_S28.GGAGATGGTTCTCGCT",
                "M7_S27.AGACTCATCATCCCGT",
                "M7_S28.CACTGAATCCGATAGT",
                "M7_S27.TGATTTCTCAGATGCT",
                "M7_S27.CAGAGCCCATCCGAAT",
                "M7_S28.ATACCTTCAGAAATTG",
                "M7_S27.TAGGTTGGTTAATGAG",
                "M7_S27.CATCCACCACGAGGTA",
                "M7_S28.CAATTTCAGAGGTTAT",
                "M7_S28.GTGGAAGGTGGACTGA",
                "M7_S27.TTCTGTATCCAACTAG",
                "M7_S27.TTTGTTGGTGCAATGG",
                "M7_S28.AAACCCACAGCGTAGA",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Study",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610007P14Rik Cells": {
            "name": "0610007P14Rik Cells",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "M1_S4.GCACATAGTCAAGCGA",
                "M1_S3.CACGTGGCATGGATCT",
                "M1_S4.CTCCACAGTTCGTAAC",
                "M1_S3.GGGTAGACAAGACCTT",
                "M1_S4.TAGCACATCTAGCCAA",
                "M1_S4.GGAATGGTCTCACCCA",
                "M1_S3.TATTCCAAGAGGCGGA",
                "M5_S30.GAGGCCTGTATCCTCC",
                "M5_S29.ACGTTCCTCTTCCCGA",
                "M5_S30.CAACGGCCACGCGTCA",
                "M5_S30.ATTCGTTCATCGAAGG",
                "M5_S30.CCTCTCCCACATTCGA",
                "M5_S30.ACTTTGTAGAGCCGAT",
                "M5_S29.TCATACTAGTTACGAA",
                "M5_S29.AGACACTGTAGAGGAA",
                "M5_S30.CATGGTACAGGCTATT",
                "M5_S29.CTTACCGAGCGAATGC",
                "M5_S30.ACTATGGAGCACACAG",
                "M6_S31.GTCTAGACATGTCGTA",
                "M6_S31.CAACAACTCGGAACTT",
                "M6_S31.GAGTCATCACACTGGC",
                "M6_S31.CCTAACCGTCCTATAG",
                "M6_S31.GTCACTCAGGTCGTAG",
                "M6_S31.TTCCGGTGTGCCTGAC",
                "M6_S31.ACAGAAATCCCTATTA",
                "M7_S28.AGGGTCCTCGAAGGAC",
                "M7_S27.CTCCCAAAGTTGCTGT",
                "M7_S28.GGTCTGGCACAGTCGC",
                "M7_S28.GAAACCTAGTAAGGGA",
                "M7_S28.GTCAAGTTCGAGCTGC",
                "M7_S28.GTGGCGTCACCGGAAA",
                "M7_S27.GCCATGGTCCCATACC",
                "M7_S28.TCAGGTATCCATAGAC",
                "M7_S28.TCAAGTGAGCAAGTCG",
                "M7_S28.GAACTGTAGTCATCCA",
                "M7_S28.GGAACCCGTGAGTAAT",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610007P14Rik Expression": {
            "name": "0610007P14Rik Expression",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
                2.0,
                1.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610009B22Rik Cells": {
            "name": "0610009B22Rik Cells",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "M1_S3.TTTGATCAGACTCAAA",
                "M1_S3.TATTCCAAGAGGCGGA",
                "M5_S30.TGTGAGTTCAACCTTT",
                "M6_S31.GACACGCGTCTTTATC",
                "M7_S27.TAACCAGCAGAAATTG",
                "M7_S27.AAGCGTTCAGCTGTGC",
                "M7_S28.TTGTGGAGTGTAAACA",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610009B22Rik Expression": {
            "name": "0610009B22Rik Expression",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "expression",
            "array_index": 0,
            "values": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610009O20Rik Cells": {
            "name": "0610009O20Rik Cells",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "M1_S3.GGCTTTCGTACGCTAT",
                "M1_S4.AACCATGGTGGCTAGA",
                "M1_S4.CCCATTGTCTGCGGCA",
                "M1_S3.TATTCCAAGAGGCGGA",
                "M5_S29.ACGTTCCTCTTCCCGA",
                "M5_S29.GGTGTCGAGACATACA",
                "M5_S29.GGTTCTCCAGGTGACA",
                "M5_S29.CTCCGATGTAAGTTGA",
                "M5_S29.GAAGGACCAATCAAGA",
                "M5_S30.ACATGCATCCTCACTG",
                "M5_S30.GGTGAAGAGAGAATCT",
                "M5_S29.CAGATACAGTAGGGTC",
                "M5_S29.GAAGCCCAGGGTGAAA",
                "M6_S31.CAATGACAGTAACCGG",
                "M6_S31.CGATGCGTCGCTGTCT",
                "M6_S31.TCGAACAAGCGCCTCA",
                "M6_S31.TCCACGTGTCTGCGCA",
                "M6_S31.GTCACTCAGGTCGTAG",
                "M7_S27.CACGTGGCAGAGGTAC",
                "M7_S27.AGTACTGCAACCTATG",
                "M7_S28.TTGTGGAGTGTAAACA",
                "M7_S28.GGTTAACTCTTACGGA",
                "M7_S27.CGATCGGCATTGCAAC",
                "M7_S28.CAATCGATCCAAAGGG",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610009O20Rik Expression": {
            "name": "0610009O20Rik Expression",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610010F05Rik Cells": {
            "name": "0610010F05Rik Cells",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "cells",
            "array_index": 0,
            "values": [
                "M1_S4.AACGTCAAGTCGCCAC",
                "M1_S3.AGATGCTGTCGAGTGA",
                "M1_S4.AGTAGTCTCGTAGTCA",
                "M1_S3.GTAGCTACAGCTTTCC",
                "M4_S13.TTGCATTTCCATTTGT",
                "M5_S29.GGTGTTACAGACAATA",
                "M5_S29.ACGTTCCTCTTCCCGA",
                "M5_S30.ATTCGTTCATCGAAGG",
                "M5_S30.CTGTATTGTTTACGAC",
                "M5_S29.TCACTATAGAGCCGAT",
                "M5_S29.TCTGCCACAGTAACGG",
                "M5_S29.ATTCAGGTCTGTGTGA",
                "M5_S29.TACAGGTAGTTGCATC",
                "M5_S29.GATTTCTCACTAGTAC",
                "M5_S29.TCATACTAGTTACGAA",
                "M5_S30.CCCTTAGGTAGTTAGA",
                "M5_S30.CATGGTACAGGCTATT",
                "M5_S30.TCAGGTAGTGAAAGTT",
                "M5_S29.TGTACAGAGAGTTGAT",
                "M5_S29.ATTACTCGTTGTATGC",
                "M5_S29.CAGATACAGTAGGGTC",
                "M6_S31.AGAAGCGCATGGTGGA",
                "M6_S31.GAGTCATCACACTGGC",
                "M6_S31.ACATCCCAGAGGTCAC",
                "M6_S31.GACACGCGTCTTTATC",
                "M6_S31.TCCACGTGTCTGCGCA",
                "M6_S31.TCACGCTAGAATTCAG",
                "M6_S31.ACAGAAAGTTTCCAAG",
                "M6_S31.AAAGGGCGTCTTCATT",
                "M6_S31.GGGTCACTCCAAGCTA",
                "M6_S31.ACAGAAATCCCTATTA",
                "M7_S28.GTTCGCTCATTGCTTT",
                "M7_S27.TGAGGGAAGTCGAATA",
                "M7_S27.AAACGAACAGAGACTG",
                "M7_S28.GGTCTGGCACAGTCGC",
                "M7_S28.AACCTGATCATTTACC",
                "M7_S28.TGGATGTGTTACAGCT",
                "M7_S27.GGAGAACCACCTAAAC",
                "M7_S27.GCCTGTTGTCGTGGTC",
                "M7_S27.TAGACTGTCCATGATG",
                "M7_S28.TTAGGGTAGCATCCCG",
                "M7_S27.GGGACTCCAACAAAGT",
                "M7_S27.TTACTGTCAATCGCCG",
                "M7_S28.GGTTAACTCTTACGGA",
                "M7_S28.ACAAGCTCACCTGAAT",
                "M7_S28.GAACTGTAGTCATCCA",
                "M7_S27.TCAGTTTGTCAGCTTA",
                "M7_S28.CCACGAGAGTGCACAG",
                "M7_S28.ACCAACAGTTGCATCA",
                "M7_S27.AATGGCTCATAGATGA",
                "M7_S27.CTCAACCTCCACAGCG",
                "M7_S27.CATCCACCACGAGGTA",
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
        "0610010F05Rik Expression": {
            "name": "0610010F05Rik Expression",
            "cluster_name": "one_column_feature_file_data_models.mtx",
            "array_type": "expression",
            "array_index": 0,
            "values": [
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
                1.0,
                1.0,
                2.0,
                1.0,
                1.0,
            ],
            "subsample_threshold": None,
            "subsample_annotation": None,
            "linear_data_type": "Gene",
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
        },
    },
    "gene_models": {
        "0610007P14Rik": {
            "name": "0610007P14Rik",
            "searchable_name": "0610007p14rik",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "gene_id": "0610007P14Rik",
        },
        "0610009B22Rik": {
            "name": "0610009B22Rik",
            "searchable_name": "0610009b22rik",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "gene_id": "0610009B22Rik",
        },
        "0610009O20Rik": {
            "name": "0610009O20Rik",
            "searchable_name": "0610009o20rik",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "gene_id": "0610009O20Rik",
        },
        "0610010F05Rik": {
            "name": "0610010F05Rik",
            "searchable_name": "0610010f05rik",
            "study_file_id": ObjectId("5dd5ae25421aa910a723a447"),
            "study_id": ObjectId("5f2f58eba0845f8c4cf1dc12"),
            "gene_id": "0610010F05Rik",
        },
    },
}
