# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: cimg/python:3.7.5

    working_directory: ~/scp-ingest-pipeline

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      # unable to install tabix with base image cimg/python:3.7.5
      # commenting out install because also no longer running test_genomes
      # if restoring test_genomes, will need to resolve tabix install issue
      # - run:
      #     name: Install system dependencies for Genomes Pipeline
      #     command: |
      #       sudo apt-get install -y tabix

      - run:
          name: Install Python dependencies
          command: |
            python --version
            pwd
            ls
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd tests
            pytest -k 'not test_genomes and not test_make_toy' --cov-report=xml --cov=../ingest/

      - codecov/upload:
          file: tests/coverage.xml
