# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.2
jobs:
  install_and_configure_cli:
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          executor: gcp-cli/default
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      - image: circleci/openjdk:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/scp-ingest-pipeline

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            gcloud beta emulators firestore start --host-port localhost:8081
            export FIRESTORE_EMULATOR_HOST=localhost:8081
            . venv/bin/activate
            cd tests
            coverage run -m pytest
            coverage report --include *scp-ingest-pipeline/ingest*
            coverage html --include *scp-ingest-pipeline/ingest*

      - store_artifacts:
          path: tests/htmlcov