# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: circleci/python:3.6.1
      - image: google/cloud-sdk:262.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/scp-ingest-pipeline

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: Install Firestore emulator
          command: |
            apt-get --yes install google-cloud-sdk google-cloud-sdk-firestore-emulator

      - run:
          name: Start Firestore emulator
          command: |
            gcloud beta emulators firestore start --host-port localhost:8081 &

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            env
            export FIRESTORE_EMULATOR_HOST=localhost:8081
            . venv/bin/activate
            cd tests
            python3 test_ingest.py
            coverage run -m pytest
            coverage report --include *scp-ingest-pipeline/ingest*
            coverage html --include *scp-ingest-pipeline/ingest*

      - store_artifacts:
          path: tests/htmlcov