# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.9-stretch

    working_directory: ~/scp-ingest-pipeline

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: Install Firestore emulator
          command: |
            # Add the Cloud SDK distribution URI as a package source
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

            # Import the Google Cloud Platform public key
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            
            # Enable `add-apt-repository` command
            sudo apt-get --yes install software-properties-common

            # Enable installation of OpenJDK, needed by gcloud
            sudo add-apt-repository --yes ppa:openjdk-r/ppa

            # Update the package list and install the Cloud SDK
            sudo apt-get --yes update && sudo apt-get --yes install google-cloud-sdk
            sudo apt-get --yes install google-cloud-sdk google-cloud-sdk-firestore-emulator

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            env
            gcloud beta emulators firestore start --host-port localhost:8081 &
            export FIRESTORE_EMULATOR_HOST=localhost:8081
            . venv/bin/activate
            cd tests
            pytest --cov=../ingest/

      - store_artifacts:
          path: tests/htmlcov