#!/bin/bash

export MONGODB_USERNAME='single_cell'
export DATABASE_NAME='single_cell_portal_development'
vault login -method=github token=`~/bin/git-vault-token`
export MONGODB_PASSWORD=`vault read secret/kdux/scp/development/$BROAD_USER/mongo/user | grep password | awk '{ print $2 }' `
export DATABASE_HOST=`vault read secret/kdux/scp/development/$BROAD_USER/mongo/hostname | grep ip | awk '{ $2=substr($2,2,length($2)-2); print $2 }' ` 
export BYPASS_MONGO_WRITES='yes'
export BARD_HOST_URL="https://terra-bard-dev.appspot.com"
